"""Add feature storage

Revision ID: b461d717943d
Revises: aea193a574c6
Create Date: 2020-09-19 21:41:52.538504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b461d717943d'
down_revision = 'aea193a574c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_vectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('features', sa.String(), nullable=False),
    sa.Column('sentiment', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feature_vectors')
    # ### end Alembic commands ###
